[WIP] refactor: pages
DivanteLtd/storefront-ui pull request #1359
Opened 2020-08-11 08:11 UTC by justyna-13

# Related issue

Closes #

# Scope of work

# Screenshots of visual changes

# Checklist

- [ ] No commented blocks of code left
- [ ] Run tests and docs
- [ ] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/contributing/coding-guidelines.html#component-rules) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

2020-09-01 10:52 UTC, AdamPawlinski requested changes
Once again, it is just amazing work @justyna-13 ! :+1:  
Only few differences with design and  I wonder if they should be necessary applied, but I have noticed them and left comments.

2020-09-01 10:52 UTC, AdamPawlinski commented on packages/vue/src/examples/pages/detailed-cart/_internal/OrderSummary.vue
>          @click="$emit('click:next')"
There are different text on buttons instead "Place my order" should be "Confirm and pay" like on design. The same on other checkout steps.

2020-09-01 10:52 UTC, AdamPawlinski commented on packages/vue/src/examples/pages/home/Home.vue
>          :key="index"
There is no "popular categories" section and the sequence of sections is different on mobile. And there is typo in "match with it" sentence.

2020-09-03 10:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/DivanteLtd/storefront-ui?pullRequest=1359) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/DivanteLtd/storefront-ui?pullRequest=1359) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: AdamPawlinski<br/>:x: justyna-13<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/DivanteLtd/storefront-ui?pullRequest=1359) it.</sub>

2020-09-03 10:49 UTC, AdamPawlinski commented
Customization docs updated.

2020-09-07 16:35 UTC, AdamPawlinski submitted a review, later dismissed

2020-10-06 06:57 UTC, filrak approved these changes

2020-10-10 21:42 UTC, mayashavin commented
@justyna-13 please review the conflict before merging.

2020-10-12 05:47 UTC, justyna-13 commented
@mayashavin done :slightly_smiling_face:

2020-10-12 06:04 UTC, merged