feat: SfAddress
DivanteLtd/storefront-ui pull request #1403
Opened 2020-09-15 13:32 UTC by justyna-13

# Related issue
Closes #

# Scope of work
New component for displaying address

# Screenshots of visual changes
![Zrzut ekranu z 2020-09-15 15-30-28](https://user-images.githubusercontent.com/46591755/93216894-91067380-f768-11ea-813e-7e0f92453e1f.png)
![Zrzut ekranu z 2020-09-15 15-30-36](https://user-images.githubusercontent.com/46591755/93216904-9368cd80-f768-11ea-90e5-8dfad0b3b26a.png)

# Checklist

- [ ] No commented blocks of code left
- [ ] Run tests and docs
- [ ] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/contributing/coding-guidelines.html#component-rules) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

2020-09-15 13:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/DivanteLtd/storefront-ui?pullRequest=1403) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/DivanteLtd/storefront-ui?pullRequest=1403) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/DivanteLtd/storefront-ui?pullRequest=1403) it.</sub>

2020-09-16 11:59 UTC, AdamPawlinski submitted a review, later dismissed
It looks perfectly for me :+1:

2020-09-16 13:45 UTC, filrak commented on packages/vue/src/components/molecules/SfAddress/SfAddress.vue
> +  <SfButton
is chackbox in button valid html? shouldn't that be "just" checkbox?

2020-09-21 07:42 UTC, AdamPawlinski requested changes

2020-09-24 07:41 UTC, AdamPawlinski submitted a review, later dismissed

2020-09-24 22:09 UTC, AdamPawlinski submitted a review, later dismissed

2020-09-25 09:37 UTC, filrak commented on packages/vue/src/components/molecules/SfAddressPicker/SfAddressPicker.vue
> +      this.checked = newVal;
please initialize this var first ;)

2020-09-28 07:37 UTC, filrak approved these changes

2020-09-28 07:37 UTC, merged