fix: SfProductCard isAddedToCart prop not changing icon
DivanteLtd/storefront-ui pull request #1432
Opened 2020-09-25 15:10 UTC by justyna-13

# Related issue
Closes #1427 

# Scope of work

# Screenshots of visual changes
NO visual changes 

# Checklist

- [ ] No commented blocks of code left
- [ ] Run tests and docs
- [ ] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/contributing/coding-guidelines.html#component-rules) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

2020-09-29 05:42 UTC, mayashavin requested changes
See my comment

2020-09-29 05:42 UTC, mayashavin commented on packages/vue/src/components/organisms/SfProductCard/SfProductCard.vue
> +                  v-if="isAddingToCart || isAddedToCart"
put this one before the other `slot` and set the other slot condition to `v-else` instead of repeating the condition just in the opposite condition

2020-10-01 19:42 UTC, mayashavin commented on packages/vue/src/components/organisms/SfProductCard/SfProductCard.vue
> +                  v-if="isAddingToCart || isAddedToCart"
Something similar to 
```
<slot
    v-if="isAddingToCart || isAddedToCart"
    name="adding-to-cart-icon"
>
</slot>
<slot v-else
 name="add-to-cart-icon
>
</slot>
```
You don't need two `v-if`

2020-10-30 10:37 UTC, AdamPawlinski approved these changes
Perefectly :+1:

2020-11-01 21:28 UTC, merged