fix: SfAddressPicker doesn't react to "selected" prop changes
DivanteLtd/storefront-ui pull request #1492
Opened 2020-10-22 10:42 UTC by justyna-13

# Related issue
Closes #1490 

# Scope of work
Changed prop name, added watch and emitted event 

# Screenshots of visual changes
No visual changes 

# Checklist

- [ ] No commented blocks of code left
- [ ] Run tests and docs
- [ ] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/contributing/coding-guidelines.html#component-rules) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

2020-10-22 10:51 UTC, Fifciu requested changes

2020-10-22 10:51 UTC, Fifciu commented on packages/vue/src/components/molecules/SfAddressPicker/SfAddressPicker.vue
> +  <div class="sf-address-picker" @change="inputHandler">
inputHandler will never be called

2020-10-22 10:51 UTC, Fifciu commented on packages/vue/src/components/molecules/SfAddressPicker/SfAddressPicker.vue
> +    value: {
Sounds like a breaking change (or maybe earlier it was like that?) - if not, you could use https://vuejs.org/v2/api/#model

2020-10-22 10:51 UTC, Fifciu commented on packages/vue/src/components/molecules/SfAddressPicker/SfAddressPicker.vue
> +    value(newVal) {
Remember to change it to `selected` if you could restore this props name

2020-10-22 10:51 UTC, Fifciu commented on packages/vue/src/components/molecules/SfAddressPicker/SfAddressPicker.vue
> +    inputHandler() {
I think instead of creating this function you could emit this event in setSelectedValue as you are providing it to the childs

2020-10-23 07:27 UTC, Fifciu approved these changes

2020-10-28 08:41 UTC, AdamPawlinski approved these changes
Great, perfectly done :+1:

2020-10-30 20:26 UTC, merged